pose_landmarker:
  joints:
    11: left shoulder
    12: right shoulder
    13: left elbow
    14: right elbow
    15: left wrist
    16: right wrist
    23: left hip
    24: right hip
    25: left knee
    26: right knee
    27: left ankle
    28: right ankle
    29: left heel
    30: right heel
    31: left foot index
    32: right foot index

  connections:
    head: [
      [0, 1], [1, 2], [2, 3], [3, 7], [0, 4], [4, 5], [5, 6], [6, 8], [10, 9]
    ]

    torso: [
      [11, 12], [11, 13], [13, 15], [15, 17], [17, 19], [19, 21], [12, 14], [14, 16], [16, 18], [18, 20], [20, 16], [16, 22],
      [12, 24], [24, 23], [11, 23],
      [24, 26], [26, 28], [28, 30], [30, 32], [32, 28], [23, 25], [25, 27], [27, 29], [29, 31], [31, 27]
    ]

joints_output_path: results
