squat:
  comparison_features: [
    left_knee_3D,
    right_knee_3D,
    left_hip_3D,
    right_hip_3D
  ]
  start:
    right_knee_3D: 165
    left_knee_3D: 165
  finish:
    right_knee_3D: 75
    left_knee_3D: 75
