squat:
  comparison_features: [
    left_knee,
    right_knee,
    left_hip,
    right_hip
  ]

  start:
    right_knee_3D: 165
    left_knee_3D: 165
  finish:
    right_knee_3D: 75
    left_knee_3D: 75
